Repository mindset-dojo/mindset-dojo.github.io, pull requests merged in 2024-07, with the labels that each got.

#28 feat: Add 4th-Person Knowing (Circles) article
  docs/_data/domains/Mindset.yaml
Labels: enhancement, mindset, red

#26 belt request
  docs/_data/members/michael-basil.yaml
Labels: belt-request, mindset, belt-claim-verified-dialog, belt-claim-verified-reflection, belt-claim-verified-formatting, belt-claim-verified-demo, green

#24 feat(Mindset): Add Self Actualization exercises to red level
  docs/_data/domains/Mindset.yaml
Labels: enhancement, mindset, red

#30 feat: Add White Level reflection
  docs/Orientation-Request.md
Labels: enhancement, white

#27 belt request
  docs/_data/members/allison-kaufmann.yaml
Labels: belt-request, mindset, belt-claim-verified-dialog, belt-claim-verified-reflection, belt-claim-verified-formatting, belt-claim-verified-demo, green

#33 feat: Belt level guidance uplift
  docs/_config.yml
Labels: enhancement, green, red, black
