Repository mindset-dojo/mindset-dojo.github.io, pull requests merged in 2025-09, with the labels that each got.

#109 feat: Clarify contribution role qualifications
  CONTRIBUTING.md
Labels: enhancement

#108 feat: Leadership Awakened
  _data/program.yaml
Labels: enhancement

#112 Mindset Dojo Insights Article about the Map of Consciousness
  _data/program.yaml
Labels: documentation

#139 Refactor of Project Page
  project.md
Labels: documentation, enhancement
